### ISSUE TITLE
Zo, of zo?

### ISSUE THREAD

**Issue by vasilisvg** [kyunwang/hva-css-minor#1]
https://github.com/kyunwang/hva-css-minor/blob/7e0ebd40d6e8453977c06897c882b08e4973df1d/app/styles.css#L6
Je kan natuurlijk een extra variabele aanmaken voor fontsizes op mobiel, maar negeer je dan niet juist het idee achter variabelen? Je kan natuurlijk ook de custom property zelf in een mediaquery stoppen. Waarbij je zegt: normale font-grootte is .9em op een scherm kleiner dan 30em, en ander 1em.

**Comment by kyunwang** [comment]
Noted. Ik ga mediaqueries gebruiken om de variabelen aan te passen
